### ISSUE TITLE
How should a quantized + compiled model be serialized? 

### ISSUE THREAD

**Issue by sayakpaul** [sayakpaul/diffusers-torchao#32]
@jerryzh168 I think this could be beneficial to be able to load a quantized and compiled model and proceed straight to inference. 

However, I am not sure what functions to use to make this happen. 

I was referring to https://github.com/pytorch/ao/tree/main/torchao/quantization#workaround-with-unwrap_tensor_subclass-for-export-aoti-and-torchcompile-pytorch-24-and-before-only, but I am still not sure if this is the right way:

<details>
<summary>Code</summary>

```python
from diffusers import DiffusionPipeline
from torchao.quantization import autoquant
from torchao.utils import unwrap_tensor_subclass
import torch

pipeline = DiffusionPipeline.from_pretrained(
    "black-forest-labs/FLUX.1-dev", torch_dtype=torch.bfloat16
).to("cuda")
# pipeline.transformer.to(memory_format=torch.channels_last)
# pipeline.transformer = torch.compile(
#     pipeline.transformer, mode="max-autotune", fullgraph=True
# )
pipeline.transformer = autoquant(pipeline.transformer)

for _ in range(1):
    _ = pipeline("dog", num_inference_steps=2)

# example_inputs = {
#     "hidden_states": torch.randn(1, 4096, 64, dtype=torch.bfloat16, device="cuda"),
#     "encoder_hidden_states": torch.randn(1, 512, 4096, dtype=torch.bfloat16, device="cuda"),
#     "pooled_projections": torch.randn(1, 768, dtype=torch.bfloat16, device="cuda"),
#     "timestep": torch.tensor([1.0], device="cuda").expand(1),
#     "img_ids": torch.randn(4096, 3, dtype=torch.bfloat16, device="cuda"),
#     "txt_ids": torch.randn(512, 3, dtype=torch.bfloat16, device="cuda"),
#     "guidance": torch.tensor([3.5],  device="cuda").expand(1),
# }
example_inputs = (
    torch.randn(1, 4096, 64, dtype=torch.bfloat16, device="cuda"),
    torch.randn(1, 512, 4096, dtype=torch.bfloat16, device="cuda"),
    torch.randn(1, 768, dtype=torch.bfloat16, device="cuda"),
    torch.tensor([1.0], device="cuda"),
    torch.randn(4096, 3, dtype=torch.bfloat16, device="cuda"),
    torch.randn(512, 3, dtype=torch.bfloat16, device="cuda"),
    torch.tensor([3.5],  device="cuda"), None, None, None, False
)

torch._export.aot_compile(pipeline.transformer, example_inputs)
```

</details>

<details>
<summary>Issue</summary>

```bash
Traceback (most recent call last):
  File "/fsx/sayak/diffusers-torchao/inference/serialize_quant_compile.py", line 37, in <module>
    torch._export.aot_compile(pipeline.transformer, example_inputs)
  File "/fsx/sayak/miniconda3/envs/diffusers/lib/python3.9/site-packages/torch/_export/__init__.py", line 287, in aot_compile
    so_path = torch._inductor.aot_compile(gm, args, kwargs, options=options)  # type: ignore[arg-type]
  File "/fsx/sayak/miniconda3/envs/diffusers/lib/python3.9/site-packages/torch/_inductor/__init__.py", line 115, in aot_compile
    return compile_fx_aot(
  File "/fsx/sayak/miniconda3/envs/diffusers/lib/python3.9/site-packages/torch/_inductor/compile_fx.py", line 1143, in compile_fx_aot
    compiled_lib_path = compile_fx(
  File "/fsx/sayak/miniconda3/envs/diffusers/lib/python3.9/site-packages/torch/_inductor/compile_fx.py", line 1253, in compile_fx
    return compile_fx(
  File "/fsx/sayak/miniconda3/envs/diffusers/lib/python3.9/site-packages/torch/_inductor/compile_fx.py", line 1295, in compile_fx
    return compile_fx(
  File "/fsx/sayak/miniconda3/envs/diffusers/lib/python3.9/site-packages/torch/_inductor/compile_fx.py", line 1491, in compile_fx
    gm, graph_signature = aot_export_module(
  File "/fsx/sayak/miniconda3/envs/diffusers/lib/python3.9/site-packages/torch/_functorch/aot_autograd.py", line 1246, in aot_export_module
    fx_g, metadata, in_spec, out_spec = _aot_export_function(
  File "/fsx/sayak/miniconda3/envs/diffusers/lib/python3.9/site-packages/torch/_functorch/aot_autograd.py", line 1480, in _aot_export_function
    fx_g, meta = create_aot_dispatcher_function(
  File "/fsx/sayak/miniconda3/envs/diffusers/lib/python3.9/site-packages/torch/_functorch/aot_autograd.py", line 522, in create_aot_dispatcher_function
    return _create_aot_dispatcher_function(
  File "/fsx/sayak/miniconda3/envs/diffusers/lib/python3.9/site-packages/torch/_functorch/aot_autograd.py", line 729, in _create_aot_dispatcher_function
    raise RuntimeError(
RuntimeError: aot_export is not currently supported with traceable tensor subclass.
If you need this feature, please comment on <CREATE_ISSUE_LINK>
```

</details>

I am on torch `2.5.0.dev20240903+cu121`, H100, on the latest commit on `torchao`. 

Could you advise? Should we not expect a serialized binary as a result of the AOT compile?

**Comment by jerryzh168** [comment]
yeah you'll need to call `unwrap_tensor_subclass` before calling `aot_compile` no matter what pytorch/torchao version you are using right now

we haven't tested the perf for this path, only made sure it runs currently: https://github.com/pytorch/ao/blob/8236a874479a9a9168e584c81dda8707f4c41006/test/quantization/test_quant_api.py#L607

**Comment by sayakpaul** [comment]
Thanks, running this currently. Some follow-up questions:

* How can I make sure the compilation uses `max-autotune` with `fullgraph=True`? 
* How can I serialize the compiled module after `torch._export.aot_compile(m_unwrapped, example_inputs)`? Would regular `torch.save(m.state_dict()` work?

**Comment by sayakpaul** [comment]
@jerryzh168 with the `unwrap_tensor_subclass()` addition, getting:

```bash
  File "/fsx/sayak/miniconda3/envs/diffusers/lib/python3.9/site-packages/torch/fx/experimental/proxy_tensor.py", line 1217, in __torch_function__
    return func(*args, **kwargs)
  File "/fsx/sayak/ao/torchao/utils.py", line 372, in _dispatch__torch_function__
    return cls._ATEN_OP_OR_TORCH_FN_TABLE[func](func, types, args, kwargs)
  File "/fsx/sayak/ao/torchao/utils.py", line 355, in wrapper
    return func(f, types, args, kwargs)
  File "/fsx/sayak/ao/torchao/quantization/linear_activation_quantized_tensor.py", line 102, in _
    return weight_tensor._quantized_linear_op(input_tensor, weight_tensor, bias)
  File "/fsx/sayak/ao/torchao/quantization/linear_activation_quantized_tensor.py", line 73, in _quantized_linear_op
    return torch.nn.functional.linear(aqt, original_weight_tensor, bias)
  File "/fsx/sayak/ao/torchao/utils.py", line 372, in _dispatch__torch_function__
    return cls._ATEN_OP_OR_TORCH_FN_TABLE[func](func, types, args, kwargs)
  File "/fsx/sayak/ao/torchao/utils.py", line 355, in wrapper
    return func(f, types, args, kwargs)
  File "/fsx/sayak/ao/torchao/dtypes/affine_quantized_tensor.py", line 1500, in _
    return weight_tensor._quantized_linear_op(input_tensor, weight_tensor, bias)
  File "/fsx/sayak/ao/torchao/dtypes/affine_quantized_tensor.py", line 224, in _quantized_linear_op
    return impl(input_tensor, weight_tensor, bias)
  File "/fsx/sayak/ao/torchao/dtypes/affine_quantized_tensor.py", line 1189, in _linear_int8_act_int8_weight_impl
    y += bias
  File "/fsx/sayak/miniconda3/envs/diffusers/lib/python3.9/site-packages/torch/_subclasses/functional_tensor.py", line 504, in __torch_dispatch__
    outs_unwrapped = func._op_dk(
RuntimeError: cannot mutate tensors with frozen storage

While executing %query : [num_users=1] = call_method[target=forward](args = (%l__self___transformer_blocks_0_attn_to_q, %x), kwargs = {})
Original traceback:
  File "/fsx/sayak/diffusers/src/diffusers/models/transformers/transformer_flux.py", line 495, in forward
    encoder_hidden_states, hidden_states = block(
  File "/fsx/sayak/diffusers/src/diffusers/models/transformers/transformer_flux.py", line 172, in forward
    attn_output, context_attn_output = self.attn(
  File "/fsx/sayak/diffusers/src/diffusers/models/attention_processor.py", line 490, in forward
    return self.processor(
  File "/fsx/sayak/diffusers/src/diffusers/models/attention_processor.py", line 1716, in __call__
    query = attn.to_q(hidden_states)
```

**Comment by jerryzh168** [comment]
I just got some example code from another PR
```
        with tempfile.TemporaryDirectory() as tmpdirname:
            print("Exporting quantized model with AOTI")
            torch._export.aot_compile(
                model,
                (activations,),
                options={"aot_inductor.output_path": f"{tmpdirname}/model.so"},
            )

            print("Running quantized model in AOTI")
            fn = torch._export.aot_load(f"{tmpdirname}/model.so", "cpu")
            fn(activations)
  ```

**Comment by sayakpaul** [comment]
Yeah loading flow is understood. 

However, it doesn't work when quantization is thrown in. Could you reproduce?

**Comment by jerryzh168** [comment]
sorry, just saw this, will take a look now

**Comment by jerryzh168** [comment]
@sayakpaul can you adapt the example for `black-forest-labs/FLUX.1-schnell`? I have some problems loading `black-forest-labs/FLUX.1-dev`

**Comment by sayakpaul** [comment]
```python
import torch
from diffusers import FluxPipeline, FluxTransformer2DModel
import torch.utils.benchmark as benchmark
from functools import partial

def get_example_inputs():
    example_inputs = {
         "hidden_states": torch.randn(1, 4096, 64, dtype=torch.bfloat16, device="cuda"),
         "encoder_hidden_states": torch.randn(1, 512, 4096, dtype=torch.bfloat16, device="cuda"),
         "pooled_projections": torch.randn(1, 768, dtype=torch.bfloat16, device="cuda"),
         "timestep": torch.tensor([1.0], device="cuda").expand(1),
         "img_ids": torch.randn(4096, 3, dtype=torch.bfloat16, device="cuda"),
         "txt_ids": torch.randn(512, 3, dtype=torch.bfloat16, device="cuda"),
         "guidance": None,
         "joint_attention_kwargs": None, 
         "return_dict": False
    }
    return example_inputs

def benchmark_fn(f, *args, **kwargs):
    t0 = benchmark.Timer(
        stmt="f(*args, **kwargs)",
        globals={"args": args, "kwargs": kwargs, "f": f},
        num_threads=torch.get_num_threads(),
    )
    return f"{(t0.blocked_autorange().mean):.3f}"

def load_model():
    model = FluxTransformer2DModel.from_pretrained(
        "black-forest-labs/FLUX.1-schnell", subfolder="transformer", torch_dtype=torch.bfloat16
    ).to("cuda")
    return model

def aot_compile(name, fn, **sample_kwargs):
    path = f"/raid/.cache/{name}.so"
    print(f"{path=}")
    options = {
        "aot_inductor.output_path": path,
        "max_autotune": True,
        "triton.cudagraphs": True,
    }

    torch._export.aot_compile(
        fn,
        (),
        sample_kwargs,
        options=options,
        disable_constraint_solver=True,
    )
    return path 

def aot_load(path):
    return torch._export.aot_load(path, "cuda")

@torch.no_grad()
def f(model, **kwargs):
    return model(**kwargs)

model = load_model()
inputs1 = get_example_inputs()
path1 = aot_compile("bs_1_1024", partial(f, model=model), **inputs1)

compiled_func_1 = aot_load(path1)
print(f"{compiled_func_1(**inputs1)[0].shape=}")

for _ in range(5):
    _ = compiled_func_1(**inputs1)[0]

time = benchmark_fn(f, compiled_func_1, **inputs1)
print(time) 
```

Would this work as a reference? I am using it for regular AOT compile.

**Comment by jerryzh168** [comment]
@sayakpaul I just tried, it gives some shape errors, does this run for you?

```
torch._dynamo.exc.TorchRuntimeError: Failed running call_function <built-in method cat of type object at 0x7fe8394f32e0>(*((FakeTensor(..., device='cuda:0', size=(512, 3), dtype=torch.bfloat16), FakeTensor(..., device='cuda:0', size=(4096, 3), dtype=torch.bfloat16)),), **{'dim': 1}):
Sizes of tensors must match except in dimension 1. Expected 512 but got 4096 for tensor number 1 in the list
```

I'm not very familiar with the model inputs, so might be easier for you to take a look

**Comment by sayakpaul** [comment]
Not sure, why is this happening. Could you pulling in the latest changes from `diffusers` main and retry? 

I just tried it and was able to obtain the following outputs:

```bash
compiled_func_1(**inputs1)[0].shape=torch.Size([1, 4096, 64])
0.144
```

<details>
<summary>Code</summary>

```python
import torch
from diffusers import FluxPipeline, FluxTransformer2DModel
import torch.utils.benchmark as benchmark
from functools import partial

def get_example_inputs():
    example_inputs = {
        "hidden_states": torch.randn(1, 4096, 64, dtype=torch.bfloat16, device="cuda"),
        "encoder_hidden_states": torch.randn(1, 512, 4096, dtype=torch.bfloat16, device="cuda"),
        "pooled_projections": torch.randn(1, 768, dtype=torch.bfloat16, device="cuda"),
        "timestep": torch.tensor([1.0], device="cuda"),
        "img_ids": torch.randn(4096, 3, dtype=torch.bfloat16, device="cuda"),
        "txt_ids": torch.randn(512, 3, dtype=torch.bfloat16, device="cuda"),
        "guidance": None,
        "joint_attention_kwargs": None, 
        "return_dict": False
    }
    return example_inputs

def benchmark_fn(f, *args, **kwargs):
    t0 = benchmark.Timer(
        stmt="f(*args, **kwargs)",
        globals={"args": args, "kwargs": kwargs, "f": f},
        num_threads=torch.get_num_threads(),
    )
    return f"{(t0.blocked_autorange().mean):.3f}"

def load_model():
    model = FluxTransformer2DModel.from_pretrained(
        "black-forest-labs/FLUX.1-schnell", subfolder="transformer", torch_dtype=torch.bfloat16
    ).to("cuda")
    return model

def aot_compile(name, fn, **sample_kwargs):
    path = f"./{name}.so"
    print(f"{path=}")
    options = {
        "aot_inductor.output_path": path,
        "max_autotune": True,
        "triton.cudagraphs": True,
    }

    torch._export.aot_compile(
        fn,
        (),
        sample_kwargs,
        options=options,
        disable_constraint_solver=True,
    )
    return path 

def aot_load(path):
    return torch._export.aot_load(path, "cuda")

@torch.no_grad()
def f(model, **kwargs):
    return model(**kwargs)

model = load_model()
inputs1 = get_example_inputs()
path1 = aot_compile("bs_1_1024", partial(f, model=model), **inputs1)

compiled_func_1 = aot_load(path1)
print(f"{compiled_func_1(**inputs1)[0].shape=}")

for _ in range(5):
    _ = compiled_func_1(**inputs1)[0]

time = benchmark_fn(f, compiled_func_1, **inputs1)
print(time) 
```

</details>

This too:

```bash
ls -lh *.so
-rwxrwxr-x 1 sayak sayak 23G Sep 25 04:14 bs_1_1024.so
```

Anything am I missing?

**Comment by jerryzh168** [comment]
@sayakpaul so the save and load works for you now? any further things we need to debug?

**Comment by sayakpaul** [comment]
@jerryzh168 we are not able to serialize quantized + AOT compiled model.

**Comment by sayakpaul** [comment]
@jerryzh168 just checking if we're clear on what's not working currently in this context and if you will have some time look into that? LMK if there's anything still unclear.

**Comment by jerryzh168** [comment]
yeah I can repro the issue now with autoquant, thanks, will take a look

error I'm getting right now is: 

```
torch._dynamo.exc.InternalTorchDynamoError: TypeError: _make_wrapper_subclass(): argument 'dtype' must be torch.dtype, not torch._C._TensorMeta
```

do you just need autoquant or `quantize_` api as well?

**Comment by sayakpaul** [comment]
I think this should be compatible with both as that covers the widest range of scenarios so far.

**Comment by jerryzh168** [comment]
@sayakpaul quantize_ works I think.

For autoquant, I think the first thing is you'll need to run with example inputs after autoquant, however there is still some model specific problem with flux, https://gist.github.com/jerryzh168/ec82a8d14b4aa848e29b56eeba750852 runs for me (need to comment out https://github.com/pytorch/pytorch/blob/d6f340f66c2a1b0bdf22377d10b073dd0e5a95d6/torch/nn/functional.py#L5993-L6022 because of some limitation in implementation of autoquant)

Seems to work with "FLUX.1-schnell" (https://gist.github.com/jerryzh168/df31131b29fdf2cfcd2055c743ead3c3) as after I modify the mha functional op, without that it will error out with stack depth too high

**Comment by sayakpaul** [comment]
I will give `quantize_()` a try first as "autoquant" workarounds feel a bit too hacky at this point. Once we have made `quantize_()` work for AoT I think we could wrap this up, pointing to https://github.com/sayakpaul/diffusers-torchao/issues/32#issuecomment-2394852945 for users interested in autoquant. 

WDYT?

**Comment by jerryzh168** [comment]
> I will give `quantize_()` a try first as "autoquant" workarounds feel a bit too hacky at this point. Once we have made `quantize_()` work for AoT I think we could wrap this up, pointing to [#32 (comment)](https://github.com/sayakpaul/diffusers-torchao/issues/32#issuecomment-2394852945) for users interested in autoquant.
> 
> WDYT?

sg for `quantize_()`

what is the workaround are you referring to for `autoquant`? commenting out https://github.com/pytorch/pytorch/blob/d6f340f66c2a1b0bdf22377d10b073dd0e5a95d6/torch/nn/functional.py#L5993-L6022 is not always required I think, and we are thinking of resolving this in autoquant itself as well.

**Comment by sayakpaul** [comment]
Ah I see. autoquant actually doesn't work yet with AoT. Not sure if this is model-specific because the trace isn't that informative. Even more weird because we know that for the same setup, `quantize_()` works.

**Comment by jerryzh168** [comment]
> Ah I see. autoquant actually doesn't work yet with AoT. Not sure if this is model-specific because the trace isn't that informative. Even more weird because we know that for the same setup, `quantize_()` works.

yeah I think you could try out different models if possible, autoquant already works with vit, but doesn't work for `FLUX.1-schnell`

**Comment by sayakpaul** [comment]
Sorry I won't have that time. 

I don't think ViT is representative of schnell because the input signatures are different in this case. Not sure how much of an impact it could have but I think you get my point.

**Comment by jerryzh168** [comment]
> Sorry I won't have that time.
> 
> I don't think ViT is representative of schnell because the input signatures are different in this case. Not sure how much of an impact it could have but I think you get my point.

OK sounds good, I think we can just talk about `quantize_` API and leave `autoquant` for the future for now, I'll try to debug the autoquant problem when I get a chance

**Comment by sayakpaul** [comment]
@jerryzh168 `quantize_()` isn't working:

```python
import torch
from diffusers import FluxPipeline, FluxTransformer2DModel
import torch.utils.benchmark as benchmark
from functools import partial
from torchao.quantization import quantize_, float8_dynamic_activation_float8_weight
from torchao.quantization.quant_api import PerRow

def get_example_inputs():
    example_inputs = {
        "hidden_states": torch.randn(1, 4096, 64, dtype=torch.bfloat16, device="cuda"),
        "encoder_hidden_states": torch.randn(1, 512, 4096, dtype=torch.bfloat16, device="cuda"),
        "pooled_projections": torch.randn(1, 768, dtype=torch.bfloat16, device="cuda"),
        "timestep": torch.tensor([1.0], device="cuda"),
        "img_ids": torch.randn(4096, 3, dtype=torch.bfloat16, device="cuda"),
        "txt_ids": torch.randn(512, 3, dtype=torch.bfloat16, device="cuda"),
        "guidance": None,
        "joint_attention_kwargs": None, 
        "return_dict": False
    }
    return example_inputs

def benchmark_fn(f, *args, **kwargs):
    t0 = benchmark.Timer(
        stmt="f(*args, **kwargs)",
        globals={"args": args, "kwargs": kwargs, "f": f},
        num_threads=torch.get_num_threads(),
    )
    return f"{(t0.blocked_autorange().mean):.3f}"

def load_model():
    model = FluxTransformer2DModel.from_pretrained(
        "black-forest-labs/FLUX.1-schnell", subfolder="transformer", torch_dtype=torch.bfloat16
    ).to("cuda")
    return model

def aot_compile(name, fn, **sample_kwargs):
    path = f"./{name}.so"
    print(f"{path=}")
    options = {
        "aot_inductor.output_path": path,
        "max_autotune": True,
        "triton.cudagraphs": True,
    }

    torch._export.aot_compile(
        fn,
        (),
        sample_kwargs,
        options=options,
        disable_constraint_solver=True,
    )
    return path 

def aot_load(path):
    return torch._export.aot_load(path, "cuda")

@torch.no_grad()
def f(model, **kwargs):
    return model(**kwargs)

model = load_model()
quantize_(model, float8_dynamic_activation_float8_weight(granularity=PerRow()))
inputs1 = get_example_inputs()
path1 = aot_compile("bs_1_1024", partial(f, model=model), **inputs1)

compiled_func_1 = aot_load(path1)
print(f"{compiled_func_1(**inputs1)[0].shape=}")

for _ in range(5):
    _ = compiled_func_1(**inputs1)[0]

time = benchmark_fn(f, compiled_func_1, **inputs1)
print(time) 
```

Error:

```bash
Traceback (most recent call last):
  File "/fsx/sayak/diffusers-torchao/aot_compile_quantized.py", line 64, in <module>
    path1 = aot_compile("bs_1_1024", partial(f, model=model), **inputs1)
  File "/fsx/sayak/diffusers-torchao/aot_compile_quantized.py", line 45, in aot_compile
    torch._export.aot_compile(
  File "/fsx/sayak/miniconda3/envs/diffusers/lib/python3.10/site-packages/torch/_export/__init__.py", line 287, in aot_compile
    so_path = torch._inductor.aot_compile(gm, args, kwargs, options=options)  # type: ignore[arg-type]
  File "/fsx/sayak/miniconda3/envs/diffusers/lib/python3.10/site-packages/torch/_inductor/__init__.py", line 157, in aot_compile
    return compile_fx_aot(
  File "/fsx/sayak/miniconda3/envs/diffusers/lib/python3.10/site-packages/torch/_inductor/compile_fx.py", line 1147, in compile_fx_aot
    compiled_lib_path = compile_fx(
  File "/fsx/sayak/miniconda3/envs/diffusers/lib/python3.10/site-packages/torch/_inductor/compile_fx.py", line 1257, in compile_fx
    return compile_fx(
  File "/fsx/sayak/miniconda3/envs/diffusers/lib/python3.10/site-packages/torch/_inductor/compile_fx.py", line 1299, in compile_fx
    return compile_fx(
  File "/fsx/sayak/miniconda3/envs/diffusers/lib/python3.10/site-packages/torch/_inductor/compile_fx.py", line 1495, in compile_fx
    gm, graph_signature = aot_export_module(
  File "/fsx/sayak/miniconda3/envs/diffusers/lib/python3.10/site-packages/torch/_functorch/aot_autograd.py", line 1246, in aot_export_module
    fx_g, metadata, in_spec, out_spec = _aot_export_function(
  File "/fsx/sayak/miniconda3/envs/diffusers/lib/python3.10/site-packages/torch/_functorch/aot_autograd.py", line 1480, in _aot_export_function
    fx_g, meta = create_aot_dispatcher_function(
  File "/fsx/sayak/miniconda3/envs/diffusers/lib/python3.10/site-packages/torch/_functorch/aot_autograd.py", line 522, in create_aot_dispatcher_function
    return _create_aot_dispatcher_function(
  File "/fsx/sayak/miniconda3/envs/diffusers/lib/python3.10/site-packages/torch/_functorch/aot_autograd.py", line 729, in _create_aot_dispatcher_function
    raise RuntimeError(
RuntimeError: aot_export is not currently supported with traceable tensor subclass.
If you need this feature, please comment on <CREATE_ISSUE_LINK>
```

**Comment by jerryzh168** [comment]
@sayakpaul will need to call

```
from torchao.utils import unwrap_tensor_subclass
unwrap_tensor_subclass(model)
```

before
```
path1 = aot_compile("bs_1_1024", partial(f, model=model), **inputs1)
```

can you try again with this?

**Comment by sayakpaul** [comment]
Did that and got:

<details>
<summary>Error</summary>

```bash
E1010 06:38:12.403000 1423370 site-packages/torch/fx/experimental/recording.py:298] failed while running evaluate_expr(*(Eq(768, s3),), **{})
Traceback (most recent call last):
  File "/fsx/sayak/diffusers-torchao/aot_compile_quantized.py", line 67, in <module>
    path1 = aot_compile("bs_1_1024", partial(f, model=model), **inputs1)
  File "/fsx/sayak/diffusers-torchao/aot_compile_quantized.py", line 46, in aot_compile
    torch._export.aot_compile(
  File "/fsx/sayak/miniconda3/envs/diffusers/lib/python3.10/site-packages/torch/_export/__init__.py", line 287, in aot_compile
    so_path = torch._inductor.aot_compile(gm, args, kwargs, options=options)  # type: ignore[arg-type]
  File "/fsx/sayak/miniconda3/envs/diffusers/lib/python3.10/site-packages/torch/_inductor/__init__.py", line 157, in aot_compile
    return compile_fx_aot(
  File "/fsx/sayak/miniconda3/envs/diffusers/lib/python3.10/site-packages/torch/_inductor/compile_fx.py", line 1147, in compile_fx_aot
    compiled_lib_path = compile_fx(
  File "/fsx/sayak/miniconda3/envs/diffusers/lib/python3.10/site-packages/torch/_inductor/compile_fx.py", line 1257, in compile_fx
    return compile_fx(
  File "/fsx/sayak/miniconda3/envs/diffusers/lib/python3.10/site-packages/torch/_inductor/compile_fx.py", line 1299, in compile_fx
    return compile_fx(
  File "/fsx/sayak/miniconda3/envs/diffusers/lib/python3.10/site-packages/torch/_inductor/compile_fx.py", line 1518, in compile_fx
    return inference_compiler(unlifted_gm, example_inputs_)
  File "/fsx/sayak/miniconda3/envs/diffusers/lib/python3.10/site-packages/torch/_inductor/compile_fx.py", line 1354, in fw_compiler_base
    return _fw_compiler_base(model, example_inputs, is_inference)
  File "/fsx/sayak/miniconda3/envs/diffusers/lib/python3.10/site-packages/torch/_inductor/compile_fx.py", line 1425, in _fw_compiler_base
    return inner_compile(
  File "/fsx/sayak/miniconda3/envs/diffusers/lib/python3.10/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/fsx/sayak/miniconda3/envs/diffusers/lib/python3.10/site-packages/torch/_inductor/compile_fx.py", line 476, in compile_fx_inner
    return wrap_compiler_debug(_compile_fx_inner, compiler_name="inductor")(
  File "/fsx/sayak/miniconda3/envs/diffusers/lib/python3.10/site-packages/torch/_dynamo/repro/after_aot.py", line 85, in debug_wrapper
    inner_compiled_fn = compiler_fn(gm, example_inputs)
  File "/fsx/sayak/miniconda3/envs/diffusers/lib/python3.10/site-packages/torch/_inductor/compile_fx.py", line 672, in _compile_fx_inner
    compiled_graph = codegen_and_compile(
  File "/fsx/sayak/miniconda3/envs/diffusers/lib/python3.10/site-packages/torch/_inductor/compile_fx.py", line 571, in codegen_and_compile
    compiled_graph = fx_codegen_and_compile(gm, example_inputs, **fx_kwargs)
  File "/fsx/sayak/miniconda3/envs/diffusers/lib/python3.10/site-packages/torch/_inductor/compile_fx.py", line 860, in fx_codegen_and_compile
    graph.run(*example_inputs)
  File "/fsx/sayak/miniconda3/envs/diffusers/lib/python3.10/site-packages/torch/_inductor/graph.py", line 780, in run
    return super().run(*args)
  File "/fsx/sayak/miniconda3/envs/diffusers/lib/python3.10/site-packages/torch/fx/interpreter.py", line 146, in run
    self.env[node] = self.run_node(node)
  File "/fsx/sayak/miniconda3/envs/diffusers/lib/python3.10/site-packages/torch/_inductor/graph.py", line 1358, in run_node
    result = super().run_node(n)
  File "/fsx/sayak/miniconda3/envs/diffusers/lib/python3.10/site-packages/torch/fx/interpreter.py", line 203, in run_node
    return getattr(self, n.op)(n.target, args, kwargs)
  File "/fsx/sayak/miniconda3/envs/diffusers/lib/python3.10/site-packages/torch/_inductor/graph.py", line 1024, in call_function
    raise LoweringException(e, target, args, kwargs).with_traceback(
  File "/fsx/sayak/miniconda3/envs/diffusers/lib/python3.10/site-packages/torch/_inductor/graph.py", line 1021, in call_function
    out = lowerings[target](*args, **kwargs)  # type: ignore[index]
  File "/fsx/sayak/miniconda3/envs/diffusers/lib/python3.10/site-packages/torch/_inductor/lowering.py", line 363, in wrapped
    out = decomp_fn(*args, **kwargs)
  File "/fsx/sayak/miniconda3/envs/diffusers/lib/python3.10/site-packages/torch/_inductor/lowering.py", line 1025, in view
    return TensorBox(View.create(x.data, sizes))
  File "/fsx/sayak/miniconda3/envs/diffusers/lib/python3.10/site-packages/torch/_inductor/ir.py", line 2475, in create
    old_size, new_size = cls.resolve_negative_size(x.get_size(), new_size)
  File "/fsx/sayak/miniconda3/envs/diffusers/lib/python3.10/site-packages/torch/_inductor/ir.py", line 2526, in resolve_negative_size
    V.graph.sizevars.guard_equals(sympy_product(old_size), sympy_product(new_size))
  File "/fsx/sayak/miniconda3/envs/diffusers/lib/python3.10/site-packages/torch/_inductor/sizevars.py", line 418, in guard_equals
    assert self.shape_env.evaluate_expr(sympy.Eq(left, right))
  File "/fsx/sayak/miniconda3/envs/diffusers/lib/python3.10/site-packages/torch/fx/experimental/recording.py", line 262, in wrapper
    return retlog(fn(*args, **kwargs))
  File "/fsx/sayak/miniconda3/envs/diffusers/lib/python3.10/site-packages/torch/fx/experimental/symbolic_shapes.py", line 5149, in evaluate_expr
    return self._evaluate_expr(orig_expr, hint, fx_node, size_oblivious, forcing_spec=forcing_spec)
  File "/fsx/sayak/miniconda3/envs/diffusers/lib/python3.10/site-packages/torch/fx/experimental/symbolic_shapes.py", line 5225, in _evaluate_expr
    static_expr = self._maybe_evaluate_static(expr,
  File "/fsx/sayak/miniconda3/envs/diffusers/lib/python3.10/site-packages/torch/fx/experimental/symbolic_shapes.py", line 1547, in wrapper
    return fn_cache(self, *args, **kwargs)
  File "/fsx/sayak/miniconda3/envs/diffusers/lib/python3.10/site-packages/torch/fx/experimental/symbolic_shapes.py", line 4494, in _maybe_evaluate_static
    vr = var_ranges[k]
torch._inductor.exc.LoweringException: KeyError: s3
  target: aten.reshape.default
  args[0]: TensorBox(StorageBox(
    InputBuffer(name='arg1660_1', layout=FixedLayout('cuda', torch.bfloat16, size=[1, 768], stride=[768, 1]))
  ))
  args[1]: [1, s3]
```

</details>

Tried `int8_weight_only()`, too but no luck.

**Comment by jerryzh168** [comment]
@sayakpaul I'll try to get a repro and post in pytorch/pytorch this week

**Comment by jerryzh168** [comment]
@sayakpaul I got a different error with pytorch nightly and torchao 0.5 and posted an issue here: https://github.com/pytorch/pytorch/issues/138254

**Comment by sayakpaul** [comment]
https://github.com/pytorch/pytorch/issues/138254#issuecomment-2422864986
